[libraries]

osvvm_common.files = [
  './osvvm_demo/OsvvmLibraries/Common/src/AddressBusResponderTransactionArrayPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/AddressBusResponderTransactionPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/AddressBusTransactionArrayPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/AddressBusTransactionPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/AddressBusVersionCompatibilityPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/FifoFillPkg_slv.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/FifoFillPtPkg_slv.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/InterruptGeneratorBit.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/InterruptGeneratorBitVti.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/InterruptGeneratorComponentPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/InterruptGlobalSignalPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/InterruptHandler.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/InterruptHandlerComponentPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/ModelParametersPtPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/ModelParametersSingletonPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/OsvvmCommonContext.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/StreamTransactionArrayPkg.vhd',
  './osvvm_demo/OsvvmLibraries/Common/src/StreamTransactionPkg.vhd',
]

osvvm.files = [
  './osvvm_demo/OsvvmLibraries/osvvm/AlertLogPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/CoveragePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/DelayCoveragePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/MemoryGenericPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/MemoryPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/MemorySupportPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/MessageListPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/MessagePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/NamePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/NameStorePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmContext.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmGlobalPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmScriptSettingsPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmScriptSettingsPkg_default.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmSettingsPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmSettingsPkg_default.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/OsvvmTypesPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/RandomBasePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/RandomPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/RandomProcedurePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/ReportPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/ResizePkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/ResolutionPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/ScoreboardGenericPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/ScoreboardPkg_int.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/ScoreboardPkg_slv.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/SortListPkg_int.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/TbUtilPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/TextUtilPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/TranscriptPkg.vhd',
  './osvvm_demo/OsvvmLibraries/osvvm/VendorCovApiPkg.vhd',
]

osvvm_axi4.files = [
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4CommonPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4InterfaceCommonPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4InterfacePkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4LiteInterfacePkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4ModelPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4OptionsArrayPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4OptionsPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/common/src/Axi4VersionCompatibilityPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamComponentPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamContext.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamGenericSignalsPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamOptionsArrayPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamOptionsPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamReceiver.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamReceiverVti.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamSignalsPkg_32.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamTbPkg.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamTransmitter.vhd',
  './osvvm_demo/OsvvmLibraries/AXI4/AxiStream/src/AxiStreamTransmitterVti.vhd',
]

lib.files = [
  './osvvm_demo/hdl/axi_stream_dut.vhd',
  './osvvm_demo/sim/test_ctrl_e.vhd',
  './osvvm_demo/sim/tb_axi_stream.vhd',
  './osvvm_demo/sim/testcases/tb_axi_stream_single_burst.vhd',
  './osvvm_demo/sim/testcases/tb_axi_stream_multi_burst.vhd',
  './osvvm_demo/sim/testcases/tb_axi_stream_corner_case.vhd',
]

